### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by zero1niner** [eshapiro42/OctoPrint-Wyze#2]
Hey Eric, Getting an error when installing: 

Installing plugin from https://github.com/eshapiro42/OctoPrint-Wyze/archive/main.zip...
/home/pi/oprint/bin/python3 -m pip --disable-pip-version-check install file:///tmp/tmp0s9xmuxb/OctoPrint-Wyze-main.zip --no-cache-dir
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing /tmp/tmp0s9xmuxb/OctoPrint-Wyze-main.zip
Requirement already satisfied: OctoPrint in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint-Wyze==0.1.4) (1.7.3)
****ERROR: Could not find a version that satisfies the requirement wyze_sdk (from octoprint-wyze)
ERROR: No matching distribution found for wyze_sdk
Error!**
Could not parse output from pip, see plugin_pluginmanager_console.log for generated output**

**Comment by eshapiro42** [comment]
Hi @zero1niner!

Unfortunately Python >=3.8 is required to install this plugin since (as you're seeing) the `wyze_sdk` module is not available for Python 3.7 or earlier.

If you still want to use it, you'll need to upgrade your OctoPrint's Python environment. Please see the bottom section "**Installing Manually**" at [this link](https://octoprint.org/download/).

**Comment by zero1niner** [comment]
Shame on me for not reading that more carefully. Thanks Eric.
