### ISSUE TITLE
Take Picture / gcode triggers

### ISSUE THREAD

**Issue by tangles-0** [eshapiro42/OctoPrint-Wyze#4]
Forgive me if this is not possible, but is it feasible to add a 'take picture' option with Wyze cameras, and gcode triggers? Could be really handy if I could trigger a photo with gcode for something like octolapse

**Comment by eshapiro42** [comment]
Hi @Energiz3r.

This _is_ technically possible, but would take a lot of doing. 

There is no simple way to define custom events based off of G-code as far as I'm aware (the exception being simple events like z-axis changes or the other events listed [here](https://docs.octoprint.org/en/master/events/index.html#gcode-processing)). I'd have to make use of another plugin like [`OctoPrint-Custom_gcode_events`](https://github.com/RoboMagus/OctoPrint-Custom_gcode_events) or else somehow intercept and parse G-code sent through OctoPrint myself and then use a [`ProgressPlugin`](https://docs.octoprint.org/en/master/plugins/mixins.html#progressplugin) or something which only has 1% granularity. I'm not immediately sure how to handle this part since this is the first plugin I've written for OctoPrint and I'm still a newbie, although I'm certain it's possible.

The library this plugin currently uses to interface with Wyze devices ([`wyze_sdk`](https://github.com/shauntarves/wyze-sdk)) does not offer access to a camera's [streams](https://github.com/shauntarves/wyze-sdk/issues/11) or any [controls](https://wyze-sdk.readthedocs.io/en/latest/wyze_sdk.api.html#cameras) other than `restart`, `turn_off` and `turn_on`. There is a module ([`wyzecam`](https://github.com/kroo/wyzecam)) which seems like it could definitely take a picture or perhaps trigger an event, but it has a lot of dependencies including [a library written in Java](https://github.com/nblavoie/wyzecam-api/tree/master/wyzecam-sdk).

I will put this on the back-burner as a "wish list" type item but I wouldn't count on it happening any time soon. Sorry I couldn't give you better news!

**Comment by tangles-0** [comment]
Greatly appreciate the detailed response, thanks!

I'll open a an issue on wyze_sdk to see if photo-taking might be possible in future but given the reverse-engineered nature of it I'd say that might be a long shot also.
